name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test
        env:
          NODE_OPTIONS: --experimental-vm-modules
        
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
        if: github.event_name == 'pull_request'
        
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            dist
            build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build- 